language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - REQUIREMENTS=complete
  - REQUIREMENTS=default

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable .

script: make test